# Generated by Django 3.2 on 2025-08-06 05:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_check'),
    ]

    operations = [
        migrations.RenameField(
            model_name='check',
            old_name='checkIOne',
            new_name='checkOne',
        ),
    ]
