# Generated by Django 3.2 on 2025-08-06 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_rename_checkione_check_checkone'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='check_for_changes',
            field=models.BooleanField(default=False),
        ),
    ]
