# Generated by Django 3.2 on 2025-08-06 06:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_choice_check_for_changes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='check',
            old_name='correct',
            new_name='correct123',
        ),
    ]
