# Generated by Django 3.2 on 2025-08-06 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_rename_correct_check_correct123'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choice',
            name='check_for_changes',
        ),
        migrations.RemoveField(
            model_name='choice',
            name='question',
        ),
    ]
